CREATE PROCEDURE WEST_WORLD.ItemDelete
@NUMEROFACTURA bigint,
@IDITEM bigint

AS
	
	DELETE FROM WEST_WORLD.Item
	WHERE idItem = @IDITEM

	DELETE FROM WEST_WORLD.Factura_Item
	WHERE numeroFactura = @NUMEROFACTURA and idItem = @IDITEM

RETURN 0

