CREATE PROCEDURE WEST_WORLD.FacturaViewOrSearch
	@NUMEROFACTURA BIGINT,
	@IDEMPRESA BIGINT,
	@IDCLIENTE BIGINT

AS	
	
	SELECT * FROM WEST_WORLD.Factura
		WHERE (@NUMEROFACTURA IS NULL OR (numeroFactura = @NUMEROFACTURA))
			AND (@IDEMPRESA IS NULL OR (empresa = @IDEMPRESA))
			AND (@IDCLIENTE IS NULL OR (cliente = @IDCLIENTE))
    
	OPTION (RECOMPILE)
RETURN 0