CREATE PROCEDURE WEST_WORLD.ItemCreate
@DESCRIPCION nvarchar(255),
@MONTO numeric(15,5),
@CANTIDAD smallint

AS
	INSERT INTO WEST_WORLD.Factura_Item(cantidad, monto)
	VALUES(@CANTIDAD, @MONTO)

	INSERT INTO WEST_WORLD.Item(descripcion)
	VALUES(@DESCRIPCION)

 OPTION (RECOMPILE)
 RETURN 0
