CREATE PROCEDURE WEST_WORLD.FacturaDelete
@NUMEROFACTURA bigint

AS
	IF EXISTS (SELECT * FROM WEST_WORLD.Factura
				WHERE numeroFactura=@NUMEROFACTURA AND pago IS NULL AND rendicion IS NULL)
		BEGIN
			DELETE FROM WEST_WORLD.Factura
			WHERE numeroFactura=@NUMEROFACTURA
			RETURN 0
		END
	ELSE 
		RETURN -1