IF OBJECT_ID('WEST_WORLD.EmpresaCreateOrUpdate') IS NOT NULL
DROP PROCEDURE WEST_WORLD.EmpresaCreateOrUpdate 

IF OBJECT_ID('WEST_WORLD.EmpresaViewOrSearch') IS NOT NULL
DROP PROCEDURE WEST_WORLD.EmpresaViewOrSearch

IF OBJECT_ID('WEST_WORLD.ClienteCreateOrUpdate') IS NOT NULL
DROP PROCEDURE WEST_WORLD.ClienteCreateOrUpdate

IF OBJECT_ID('WEST_WORLD.ClienteViewOrSearch') IS NOT NULL
DROP PROCEDURE WEST_WORLD.ClienteViewOrSearch

IF OBJECT_ID('WEST_WORLD.GetEmpresas') IS NOT NULL
DROP PROCEDURE WEST_WORLD.GetEmpresas

IF OBJECT_ID('WEST_WORLD.GetRubros') IS NOT NULL
DROP PROCEDURE WEST_WORLD.GetRubros

IF OBJECT_ID('WEST_WORLD.GetClientes') IS NOT NULL
DROP PROCEDURE WEST_WORLD.GetClientes

IF OBJECT_ID('WEST_WORLD.SucursalViewOrSearch') IS NOT NULL
DROP PROCEDURE [WEST_WORLD].[SucursalViewOrSearch]

IF OBJECT_ID('WEST_WORLD.SucursalCreateOrUpdate') IS NOT NULL
DROP PROCEDURE [WEST_WORLD].[SucursalCreateOrUpdate]

IF OBJECT_ID('WEST_WORLD.FacturaCreateOrUpdate') IS NOT NULL
DROP PROCEDURE [WEST_WORLD].[FacturaCreateOrUpdate]

IF OBJECT_ID('WEST_WORLD.FacturaViewOrSearch') IS NOT NULL
DROP PROCEDURE [WEST_WORLD].[FacturaViewOrSearch]

IF OBJECT_ID('WEST_WORLD.ItemCreateOrUpdate') IS NOT NULL
DROP PROCEDURE [WEST_WORLD].[ItemCreateOrUpdate]

IF OBJECT_ID('WEST_WORLD.ItemViewOrSearch') IS NOT NULL
DROP PROCEDURE [WEST_WORLD].[ItemViewOrSearch]

