IF OBJECT_ID('WEST_WORLD.EmpresaCreateOrUpdate') IS NOT NULL
DROP PROCEDURE WEST_WORLD.EmpresaCreateOrUpdate 

IF OBJECT_ID('WEST_WORLD.EmpresaViewOrSearch') IS NOT NULL
DROP PROCEDURE WEST_WORLD.EmpresaViewOrSearch

IF OBJECT_ID('WEST_WORLD.ClienteCreateOrUpdate') IS NOT NULL
DROP PROCEDURE WEST_WORLD.ClienteCreateOrUpdate

IF OBJECT_ID('WEST_WORLD.ClienteViewOrSearch') IS NOT NULL
DROP PROCEDURE WEST_WORLD.ClienteViewOrSearch

IF OBJECT_ID('WEST_WORLD.GetEmpresas') IS NOT NULL
DROP PROCEDURE WEST_WORLD.GetEmpresas

IF OBJECT_ID('WEST_WORLD.SucursalViewOrSearch') IS NOT NULL
DROP PROCEDURE [WEST_WORLD].[SucursalViewOrSearch]

IF OBJECT_ID('WEST_WORLD.SucursalCreateOrUpdate') IS NOT NULL
DROP PROCEDURE [WEST_WORLD].[SucursalCreateOrUpdate]

IF OBJECT_ID('WEST_WORLD.SucursalViewOrSearch') IS NOT NULL
DROP PROCEDURE [WEST_WORLD].[SucursalViewOrSearch]


