--IMPORTANTE: SE DEBE MANTENER EL ORDEN DE LOS DROP PARA QUE NO ROMPA
--Primero se eliminan las tablas con que tengan una fk hacia otra tabla 
-- y que ninguna otra tabla la referencie mediante una fk

IF OBJECT_ID('WEST_WORLD.Rol_Funcionalidad', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Rol_Funcionalidad 

IF OBJECT_ID('WEST_WORLD.Funcionalidad', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Funcionalidad 

IF OBJECT_ID('WEST_WORLD.Rol_Usuario', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Rol_Usuario

IF OBJECT_ID('WEST_WORLD.Rol', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Rol

IF OBJECT_ID('WEST_WORLD.Factura_Item', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Factura_Item

IF OBJECT_ID('WEST_WORLD.Item', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Item

IF OBJECT_ID('WEST_WORLD.Factura', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Factura

IF OBJECT_ID('WEST_WORLD.Rendicion', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Rendicion

IF OBJECT_ID('WEST_WORLD.Empresa', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Empresa 

IF OBJECT_ID('WEST_WORLD.Rubro', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Rubro 

IF OBJECT_ID('WEST_WORLD.Pago', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Pago 

IF OBJECT_ID('WEST_WORLD.FormaPago', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.FormaPago

IF OBJECT_ID('WEST_WORLD.Cliente', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Cliente

IF OBJECT_ID('WEST_WORLD.Sucursal', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Sucursal

IF OBJECT_ID('WEST_WORLD.Usuario', 'U') IS NOT NULL
DROP TABLE WEST_WORLD.Usuario